# netlify.toml

[build]
  command = "npm run build" # Assuming this is correct based on logs
  publish = ".next"         # Assuming this is correct based on logs

# Minimal SPA rewrite rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 